### ISSUE TITLE
Getting SyntaxError: Unexpected token, I think it's due to the optional chaining.

### ISSUE THREAD

**Issue by ukhanzada-nisum-com** [unjs/unplugin#315] opened 2023-06-16 00:36 UTC
### Environment

```
"webpack": "^4.44.2",
"@sentry/webpack-plugin": "^2.2.2",
node: 12
```

### Reproduction
When I am trying to build my app it gives me the error if I remove the below line it'll start working.
`const { sentryWebpackPlugin } = require("@sentry/webpack-plugin");` 

### Describe the bug

`const setup = (plugin) => plugin.esbuild?.setup ?? ((pluginBuild) => {`
SyntaxError: Unexpected token.

<img width="877" alt="Screen Shot 2023-06-15 at 5 28 09 PM" src="https://github.com/unjs/unplugin/assets/38420106/59b11e4e-489e-4708-ab3b-c7227e660a25">

**Comment by antfu** [comment] 2023-06-16 11:10
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by antfu** [comment] 2023-06-16 11:10
You should upgrade your node. v12 is EOL

**Closed by antfu** 2023-06-16 11:10 UTC

**Comment by pengfeir** [comment] 2023-06-28 08:39
I use node14.19.0 .has same question

**Comment by pengfeir** [comment] 2023-06-28 08:40
<img width="578" alt="image" src="https://github.com/unjs/unplugin/assets/22837913/87dc6409-7947-4544-9e68-183d4b3f06bb">
