### ISSUE TITLE
运行和打包报错

### ISSUE THREAD

**Issue by 986823307** [unjs/unplugin#189] opened 2022-11-01 04:38 UTC
![image](https://user-images.githubusercontent.com/56620683/199159751-c53d3279-fabb-4b14-976a-2fbfe4ebfbe1.png)
![image](https://user-images.githubusercontent.com/56620683/199159818-44521439-8cca-4796-8789-78fe1e7062ff.png)
版本：
"unplugin-auto-import": "^0.11.4"
"unplugin-vue-components": "^0.22.9"

**Comment by antfu** [comment] 2022-11-01 06:31
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-11-01 06:31 UTC
