### ISSUE TITLE
can't resolve virutal id in resolveId hook

### ISSUE THREAD

**Issue by HomyeeKing** [unjs/unplugin#451] opened 2024-12-25 12:24 UTC
### Environment

unplugin@2.1.0
node@20.16.0

### Reproduction

https://github.com/HomyeeKing/webpack-repro

### Describe the bug

```js
// src/index.js
import { a } from 'virtual:test';
console.log('a', a);
```
there's a virtual file request in `src/index.js`, I tried to use unplugin to help webpack load it, but can't get the id

### Additional context
the plugin is in `unplugins/virtualPlugin.js`
excute `pnpm run build`, 

expect see log in terminal like `id1112 virtual:test`

**Comment by sxzz** [comment] 2024-12-26 13:49
Duplicate of https://github.com/unjs/unplugin/issues/19

**Closed by sxzz** 2024-12-26 13:49 UTC
Labels: bug
